"""
Django settings for tsProject project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!z2(us&2m0d24_3l5)ki*b(d+mivk$)z#z!zo)9by+5_-==q-1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ==================== ALLOWED_HOSTS (MODIFICADO PARA RED LOCAL) ====================
# Permite acceso desde otras computadoras en la misma red
ALLOWED_HOSTS = [
    
    'localhost',
    '127.0.0.1',
    '172.20.10.3',      # Tu IP actual (Wi-Fi)
    '172.20.10.2',      # IP de la otra PC
    '*',                # Permite cualquier IP (útil para pruebas locales)
]
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'https://cussed-cilantro-oboe.ngrok-free.dev',
]

# ==================== WebRTC Configuration ====================
_default_ice_servers = [
    {'urls': 'stun:stun.l.google.com:19302'},
    {'urls': 'stun:global.stun.twilio.com:3478'},
]

WEBRTC_ICE_SERVERS = _default_ice_servers
WEBRTC_ICE_SERVERS_JSON = os.getenv('WEBRTC_ICE_SERVERS_JSON', '').strip()
if WEBRTC_ICE_SERVERS_JSON:
    try:
        parsed_ice_servers = json.loads(WEBRTC_ICE_SERVERS_JSON)
        if isinstance(parsed_ice_servers, list) and parsed_ice_servers:
            WEBRTC_ICE_SERVERS = parsed_ice_servers
    except json.JSONDecodeError:
        WEBRTC_ICE_SERVERS = _default_ice_servers

WEBRTC_TURN_URL = os.getenv('WEBRTC_TURN_URL', '').strip()
WEBRTC_TURN_USERNAME = os.getenv('WEBRTC_TURN_USERNAME', '').strip()
WEBRTC_TURN_CREDENTIAL = os.getenv('WEBRTC_TURN_CREDENTIAL', '').strip()
if WEBRTC_TURN_URL:
    turn_server = {
        'urls': WEBRTC_TURN_URL,
        'username': WEBRTC_TURN_USERNAME,
        'credential': WEBRTC_TURN_CREDENTIAL,
    }
    if turn_server not in WEBRTC_ICE_SERVERS:
        WEBRTC_ICE_SERVERS.append(turn_server)


# Application definition
INSTALLED_APPS = [
    'daphne',
    'channels',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tsProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tsProject.wsgi.application'
ASGI_APPLICATION = 'tsProject.asgi.application'

# Channels Configuration
if os.getenv('USE_INMEMORY_CHANNEL_LAYER', '0') == '1':
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')],
            },
        },
    }


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'chat-index'
LOGOUT_REDIRECT_URL = 'login'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'