# Generated by Copilot on 2026-04-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_room_created_by_message_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.FileField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="kind",
            field=models.CharField(
                choices=[("chat", "Chat"), ("voice", "Voz")],
                default="chat",
                max_length=10,
            ),
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["kind", "name"]},
        ),
    ]
