# Generated by Django 6.0.3 on 2026-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile_room_kind'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_room_id_645da7_idx',
            old_name='chat_messag_room_id_a07995_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_timesta_6494d7_idx',
            old_name='chat_messag_timesta_54d6d5_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
